package unbound_test

import (
	"strings"
	"testing"

	"github.com/home-operations/config-sidecar/internal/endpoint"
	unboundprovider "github.com/home-operations/config-sidecar/internal/provider/unbound"
)

func TestUnboundProvider_Name(t *testing.T) {
	p := unboundprovider.New("192.168.1.1", "A", 0)
	if got := p.Name(); got != "unbound" {
		t.Errorf("Name() = %q, want %q", got, "unbound")
	}
}

func TestUnboundProvider_DefaultRecordType(t *testing.T) {
	p := unboundprovider.New("192.168.1.1", "", 0)
	if p.RecordType != "A" {
		t.Errorf("RecordType = %q, want %q", p.RecordType, "A")
	}
}

func TestUnboundProvider_Render_Empty(t *testing.T) {
	p := unboundprovider.New("192.168.1.1", "A", 0)
	data, err := p.Render(nil)
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}
	// Should at least contain the generated comment.
	if !strings.Contains(string(data), "# Generated by sidecar") {
		t.Errorf("expected generated comment in output, got:\n%s", string(data))
	}
	// Should not contain any local-data entries.
	if strings.Contains(string(data), "local-data") {
		t.Errorf("expected no local-data entries for empty input, got:\n%s", string(data))
	}
}

func TestUnboundProvider_Render_SingleEndpoint(t *testing.T) {
	p := unboundprovider.New("192.168.1.100", "A", 0)
	endpoints := []*endpoint.Endpoint{
		{Name: "myapp", URL: "https://myapp.example.com", Interval: "1m"},
	}

	data, err := p.Render(endpoints)
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	content := string(data)
	if !strings.Contains(content, `local-data: "myapp.example.com. A 192.168.1.100"`) {
		t.Errorf("expected local-data record in output, got:\n%s", content)
	}
}

func TestUnboundProvider_Render_WithTTL(t *testing.T) {
	p := unboundprovider.New("10.0.0.1", "A", 300)
	endpoints := []*endpoint.Endpoint{
		{Name: "app", URL: "https://app.home.example.com", Interval: "1m"},
	}

	data, err := p.Render(endpoints)
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	content := string(data)
	if !strings.Contains(content, `local-data: "app.home.example.com. 300 A 10.0.0.1"`) {
		t.Errorf("expected TTL in local-data record, got:\n%s", content)
	}
}

func TestUnboundProvider_Render_AAAARecord(t *testing.T) {
	p := unboundprovider.New("fd00::1", "AAAA", 0)
	endpoints := []*endpoint.Endpoint{
		{Name: "v6app", URL: "https://v6.example.com", Interval: "1m"},
	}

	data, err := p.Render(endpoints)
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	content := string(data)
	if !strings.Contains(content, `local-data: "v6.example.com. AAAA fd00::1"`) {
		t.Errorf("expected AAAA record in output, got:\n%s", content)
	}
}

func TestUnboundProvider_Render_SkipsEmptyURL(t *testing.T) {
	p := unboundprovider.New("192.168.1.1", "A", 0)
	endpoints := []*endpoint.Endpoint{
		{Name: "no-url", URL: "", Interval: "1m"},
		{Name: "valid", URL: "https://valid.example.com", Interval: "1m"},
	}

	data, err := p.Render(endpoints)
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "valid.example.com") {
		t.Errorf("expected valid endpoint in output, got:\n%s", content)
	}
	if strings.Contains(content, "no-url") {
		t.Errorf("endpoint with empty URL should be skipped, got:\n%s", content)
	}
}

func TestUnboundProvider_Render_SortedAlphabetically(t *testing.T) {
	p := unboundprovider.New("192.168.1.1", "A", 0)
	endpoints := []*endpoint.Endpoint{
		{Name: "z-app", URL: "https://z.example.com", Interval: "1m"},
		{Name: "a-app", URL: "https://a.example.com", Interval: "1m"},
		{Name: "m-app", URL: "https://m.example.com", Interval: "1m"},
	}

	data, err := p.Render(endpoints)
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	content := string(data)
	aPos := strings.Index(content, "a.example.com")
	mPos := strings.Index(content, "m.example.com")
	zPos := strings.Index(content, "z.example.com")

	if aPos == -1 || mPos == -1 || zPos == -1 {
		t.Fatalf("expected all hostnames in output, got:\n%s", content)
	}

	if aPos >= mPos || mPos >= zPos {
		t.Errorf("records should be sorted alphabetically: a=%d m=%d z=%d\noutput:\n%s", aPos, mPos, zPos, content)
	}
}

func TestUnboundProvider_Render_TrailingDot(t *testing.T) {
	p := unboundprovider.New("192.168.1.1", "A", 0)
	endpoints := []*endpoint.Endpoint{
		{Name: "app", URL: "https://app.example.com", Interval: "1m"},
	}

	data, err := p.Render(endpoints)
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	// The hostname in the record must end with a dot (FQDN).
	if !strings.Contains(string(data), "app.example.com.") {
		t.Errorf("expected trailing dot in FQDN, got:\n%s", string(data))
	}
}

func TestUnboundProvider_Render_URLWithPort(t *testing.T) {
	p := unboundprovider.New("192.168.1.1", "A", 0)
	endpoints := []*endpoint.Endpoint{
		{Name: "svc", URL: "tcp://svc.example.com:5432", Interval: "1m"},
	}

	data, err := p.Render(endpoints)
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	content := string(data)
	// Port should not appear in the DNS record.
	if strings.Contains(content, ":5432") {
		t.Errorf("port should not appear in DNS record, got:\n%s", content)
	}
	if !strings.Contains(content, "svc.example.com") {
		t.Errorf("expected hostname without port in output, got:\n%s", content)
	}
}
