package unbound

import (
	"bytes"
	"fmt"
	"net/url"
	"sort"
	"time"

	"github.com/home-operations/gatus-sidecar/internal/endpoint"
	"github.com/home-operations/gatus-sidecar/internal/provider"
)

// Provider generates Unbound local DNS configuration from discovered endpoints.
// Each endpoint's hostname (extracted from its URL) is mapped to DefaultIP via
// a local-data record.
type Provider struct {
	// DefaultIP is the IP address written into every local-data record.
	DefaultIP string
	// RecordType is the DNS record type, e.g. "A" or "AAAA". Defaults to "A".
	RecordType string
	// TTL is an optional DNS TTL (seconds). When 0 the field is omitted from
	// the record so that Unbound uses its own default TTL.
	TTL int
}

var _ provider.Provider = (*Provider)(nil)

// New creates a new Unbound provider.
// recordType defaults to "A" when empty.
func New(defaultIP, recordType string, ttl int) *Provider {
	if recordType == "" {
		recordType = "A"
	}
	return &Provider{
		DefaultIP:  defaultIP,
		RecordType: recordType,
		TTL:        ttl,
	}
}

// Name returns the provider identifier.
func (p *Provider) Name() string {
	return "unbound"
}

// Render produces an Unbound-compatible configuration snippet with one
// local-data entry per endpoint. Entries are sorted alphabetically by
// hostname for deterministic output.
func (p *Provider) Render(endpoints []*endpoint.Endpoint) ([]byte, error) {
	type record struct {
		hostname string
		line     string
	}

	records := make([]record, 0, len(endpoints))

	for _, e := range endpoints {
		hostname, err := extractHostname(e.URL)
		if err != nil || hostname == "" {
			continue
		}

		// Ensure FQDN with trailing dot.
		if hostname[len(hostname)-1] != '.' {
			hostname += "."
		}

		var line string
		if p.TTL > 0 {
			line = fmt.Sprintf("local-data: \"%s %d %s %s\"\n", hostname, p.TTL, p.RecordType, p.DefaultIP)
		} else {
			line = fmt.Sprintf("local-data: \"%s %s %s\"\n", hostname, p.RecordType, p.DefaultIP)
		}

		records = append(records, record{hostname: hostname, line: line})
	}

	// Sort by hostname for deterministic output.
	sort.Slice(records, func(i, j int) bool {
		return records[i].hostname < records[j].hostname
	})

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "# Generated by sidecar at %s\n", time.Now().UTC().Format(time.RFC3339))
	for _, r := range records {
		buf.WriteString(r.line)
	}

	return buf.Bytes(), nil
}

// extractHostname parses rawURL and returns the hostname without port.
// Returns an empty string for empty or unparseable inputs.
func extractHostname(rawURL string) (string, error) {
	if rawURL == "" {
		return "", nil
	}
	u, err := url.Parse(rawURL)
	if err != nil {
		return "", err
	}
	return u.Hostname(), nil
}
