name: Lint
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    # renovate: datasource=github-tags depName=DevSecNinja/.github
    uses: DevSecNinja/.github/.github/workflows/lint.yml@52ead33a69740e725ec35d4d92304571be0ad3df # main
    permissions:
      contents: read
      security-events: write
    with:
      # renovate: datasource=github-releases depName=jdx/mise
      mise-version: "2026.5.10"
      # renovate: datasource=github-releases depName=golangci/golangci-lint
      golangci-lint-version: "v2.12.2"
      lint-dprint: false
      lint-yamllint: false
      lint-gitleaks: false
      lint-shellcheck: false
      lint-shfmt: false
      lint-checkov: false
      lint-trivy: false
      lint-zizmor: false
      lint-config-drift: false
